name: quiz_app
description: A Flutter project for a quiz application with categories, authentication, analytics, and gamification features.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.8.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.2
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.4.3
  google_sign_in: ^6.1.6
  
  # Local Storage
  sqflite: ^2.4.0
  path: ^1.9.0
  shared_preferences: ^2.3.2
  
  # UI
  google_fonts: ^6.2.1
  
  # Utilities
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
