name: quiz_app
description: A Flutter project for a quiz application with categories, authentication, analytics, and gamification features.
publish_to: 'none' # Remove this line if you're planning to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '^3.5.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2
  firebase_analytics: ^11.3.3
  firebase_crashlytics: ^4.1.3
  google_sign_in: ^6.1.6

  # Local DB & Storage
  sqflite: ^2.4.0
  path: ^1.9.0
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # State Management
  flutter_riverpod: ^2.5.1

  # UI & Animations
  google_fonts: ^6.2.1
  animations: ^2.0.11
  flutter_staggered_animations: ^1.1.1
  lottie: ^3.1.2
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0

  # Charts
  fl_chart: ^1.0.0

  # Networking
  dio: ^5.7.0
  connectivity_plus: ^6.0.5
  internet_connection_checker: ^3.0.1

  # Images & Media
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  photo_view: ^0.15.0

  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.1
  url_launcher: ^6.3.1
  share_plus: ^11.0.0
  package_info_plus: ^8.0.2
  device_info_plus: ^11.5.0

  # Loading & Indicators
  loading_animation_widget: ^1.2.1
  flutter_spinkit: ^5.2.1

  # Icons & UI Enhancements
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.10+1
  heroicons: ^0.11.0

  # Audio
  audioplayers: ^6.1.0

  # Device Features
  permission_handler: ^12.0.1
  vibration: ^3.1.3
  wakelock_plus: ^1.2.8

  # Notifications & Feedback
  fluttertoast: ^8.2.8
  overlay_support: ^2.1.0
  flash: ^3.1.1

  # Navigation & Routing
  go_router: ^16.0.0

  # JSON Serialization
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0

  # Security
  crypto: ^3.0.5
  encrypt: ^5.0.3

  # Time & Date
  timeago: ^3.7.0
  jiffy: ^6.3.1

  # Form Validation
  form_validator: ^2.1.1
  reactive_forms: ^18.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^6.0.0
  very_good_analysis: ^9.0.0

  # Testing
  mockito: ^5.4.4
  mocktail: ^1.0.4
  integration_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  freezed: ^3.1.0
  auto_route_generator: ^10.1.0

  # Dev Tools
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1
  change_app_package_name: ^1.3.0

flutter:
  uses-material-design: true
